### PR TITLE
Feature/persist stream

### PR DESCRIPTION
**Pull request by enyone**
- Added ability to persist streaming to DLNA device even if the sink is "silent" (no playback streams)
- Default sample rate set to 48kHz

### CODE REVIEW

**Comment by enyone** [comment]
This is because some UPNP implementations are so rubbish that frequent play/stop command eventually make the device firmware crash. Also some apps use pulseaudio in a way that causes many new streams to sink appear in a small time scale causing many stop-start command pairs sent to device in vain.

**Comment by masmu** [comment]
First, thank you for your pull request!

I addressed the problem with many play/stop commands in a small time scale before. Please take a look at that [commit](https://github.com/masmu/pulseaudio-dlna/commit/3738aa8339fdd8ef6f7737d776959f384e0c62d7). Later I increased the delay to 1 second [here](https://github.com/masmu/pulseaudio-dlna/commit/bce19fb2de58721d69594eb887950ac21cb31973). Shouldn't that solve the problem?
Besides that, is there another use case for the `--persist-stream` flag?

I tested that branch and i makes my devices play in slow motion :wink:
I assume this is about the change from 44.1khz to 48khz.
If i do a `pactl list sink-inputs` while playing music i get:
```
Senkeneingabe #4
        Treiber: protocol-native.c
        Besitzermodul: 11
        Client: 12
        Senke: 5
        Sample-Spezifikation: s16le 2ch 44100Hz
        Kanalzuordnung: front-left,front-right
        Format: pcm, format.sample_format = "\"s16le\""  format.rate = "44100"  format.channels = "2"  format.channel_map = "\"front-left,front-right\""
        Corked: no
        Lautlos: no
        Lautstärke: 0: 100% 1: 100%
                0: 0,00 dB 1: 0,00 dB
                Balance 0,00
        Pufferlatenz: 981678 usec
        Senkenlatenz: 9253 usec
        Resample-Methode: k. A.
        Eigenschaften:
                media.role = "music"
                media.name = "Spotify"
                application.name = "Spotify"

```
The important line is the `Sample-Spezifikation: s16le 2ch 44100Hz` ... Could you do the same?
What is your OS?

**Comment by masmu** [comment]
There were some serious problems when building the encoder commands. Please merge back master into here.

**Comment by masmu** [comment]
I discovered why my devices play in slow motion. I happens when using the mp3 encoder. You forgot to adjust the sample rate there. The same for _aac_ and _ogg_.

**Comment by enyone** [comment]
I will fix these and create another pull request.
After wondering a while I will also set sample rate back to 44.1kHz because that is PulseAudio default in most of the Linux distros.

**Comment by enyone** [comment]
> Please take a look at that commit. Later I increased the delay to 1 second here. Shouldn't that solve the problem?

No. My Onkyo TX-NR509 (with latest firmware) dies after whatever stop-command whenever sent :) I would strongly prefer an ability to skip stop commands totally (except when killing pulseaudio-dlna).

**Pull request closed without merging**
