### PR TITLE
upgrade use of psutil to v2.0.0+

### PR DESCRIPTION
**Pull request by klaernie**
the old v1.2.1 branch of psutil is officially deprecated, and neither
Debian nor Ubuntu have it in their stable releases anymore.

### CODE REVIEW

**Comment by masmu** [comment]
Hey, Thank you very much for figuring that out!

As far as I can see you are right about _debian_, but since _trusty_ is still shipping _**1.2.1**-1ubuntu2_ i would prefer a solution which supports both versions.

**Comment by klaernie** [comment]
well, this means we have to work around by wrapping the psutils modules. let me build a shim, I'll update the pull once done.

**Comment by Cygn** [comment]
FYI, fedora has currently psutils-1.23, up to rawhide.

**Comment by Cygn** [comment]
oups, F22 have **python**-psutil-2.1.3 and and F21 python-psutil-1.2.1
pa-dlna works fine as it is in both.

**Comment by masmu** [comment]
@Cygn Did you try to run it as root? Since the problem klaernie is referring to just appears as root.

**Comment by Cygn** [comment]
This is on F22:

    $ sudo pulseaudio-dlna --debug 2>&1 | tee -a debug.log
    11-03 12:39:19 pulseaudio_dlna.__main__                       INFO     Running as root. Starting daemon ...
    11-03 12:39:19 pulseaudio_dlna.daemon                         INFO     Checking pulseaudio processes ...
    11-03 12:39:23 pulseaudio_dlna.daemon                         INFO     Checking pulseaudio processes ...
    11-03 12:39:38 pulseaudio_dlna.daemon                         INFO     Checking pulseaudio processes ...
    11-03 12:39:46 pulseaudio_dlna.daemon                         INFO     Checking pulseaudio processes ...
    11-03 12:39:55 pulseaudio_dlna.daemon                         INFO     Checking pulseaudio processes ...
    11-03 12:40:03 pulseaudio_dlna.daemon                         INFO     Checking pulseaudio processes ...

and it just sits there. 

  

No warnings, nor errors but nothing happens.

**Comment by masmu** [comment]
Thats the bug. Normally it should detect the _pulseaudio_ process and attach a _pulseaudio-dlna_ session to it.

klaernie found out that my code works for psutils 1.x but not for 2.x. Most distributions ship 2.x but since there are some still shipping 1.x we need to support both.

**Comment by Cygn** [comment]
:+1:

**Comment by masmu** [comment]
I created the [shim](https://github.com/masmu/pulseaudio-dlna/tree/bug/psutils2) and found a few bugs while doing that. Reviews welcome!

By the way: Is it normal that there is second a _pulseaudio_ process in _gdm_ context running?

**Comment by klaernie** [comment]
I just updated my branch with my tries. Although it's not finished you might find my approach interesting. I also went for the route of using the v2.x API. My next step would be catching the exceptions generated when running against v1.x psutils, so that in the 'best case' (v2.x psutils) there is no additional overhead checking against the version number for every call.

The second pulseaudio would be quite expected - gdm's GTK and I think Unity launcher are stripped down desktop sessions, that might produce sound (failed login, speech assistence etc). And as pulseaudio per design is running for each user, I wouldn't consider this unusual. The harder part is: should this second PA still run around once a user has logged in? Should we work with both PAs?

**Comment by klaernie** [comment]
As a review of your psutils2 branch:
I personally wouldn't like to call the internals of psutils, and would rather try shimming on the outside.

My trials got stalled a little, as I don't have an Ubuntu Trusty around, as you may guess I am a Debian user. I now started to dabble with Vagrant, so that we could have a canonical testsetup, but multicast bit me once again, so got dragged into the rabbithole of stracing the ssdp-listener inside the VM, but couldn't figure it out yet. Well, time is always short, isn't it.

**Comment by masmu** [comment]
You are right about checking the version every time. I changed that in my branch.

I was thinking about cloning the module as you did, but from my perspective code can get unnecessarily complicated with doing that. And since we are using only a very limited set of methods and classes I was thinking that this is more straight forward. But If we would use much more of that module I would do it exactly like you did.

I really do not like to call _psutils_ internals, but since they are using some kind of `@cached_property` I found no other way of doing it. And since time is spare that seemed to be a good compromise instead of spending hours how to call the original property. But if you know how to do it, patches very welcome.

I was surprised by the second _pulseaudio_ process, because there is no one with _trusty_. But it absolutely makes sense. And to answer your question: I think we should not deal with the _gdm_ one.
But how do we sort it out? Something like:
```python
if process.uid_name not in ['gdm', 'lightdm']:
   ...
```
Or is there some kind of property all display manager processes have in common?

**Comment by klaernie** [comment]
Well, I suppose there is no real common denominator between all display managers. Also you should consider systems where more than one user is logged on. There are two main cases. The first would be two users sharing the same virtual terminal (one or the other is active) and true multiseats, where both users can be active simultanously. In both cases the solution for the daemon mode would be serving both users. This would mean a shared device discovery but a per-user instance of actually routing audio data, locking a renderer as soon as it get's in use.
We could also take a look at how pulseaudio is handling such cases with one or more soundcards.

I noticed that in [pulseaudio_dlna/utils/psutil.py:33](https://github.com/masmu/pulseaudio-dlna/compare/bug/psutils2#diff-a480f015277df41b7d93b4b8389488e7R32) you once again use the psutil._error exceptions, which shouldn't be neccesary as the [v1.2.1 code](https://github.com/giampaolo/psutil/blob/c32ebbc22a986559ed83dbe0360ff1c65ded6206/psutil/__init__.py#L53) already imports them into the main `psutil` namespace.

Also I found in my trials, that it might be helpful to notify the user, if we can't find all required environment variables. This way the user would know for example, that the DBUS modules was not loaded in PA, or that PA simply has to be restarted.

**Comment by klaernie** [comment]
What problem occurred with the `@cached_property`? From my perspective there is nothing wrong with  simply returning the original property.

**Comment by masmu** [comment]
```
  File "/home/masmu/git/pulseaudio-dlna/pulseaudio_dlna/utils/psutil.py", line 55, in name
    return psutil.Process.name(self)
  File "/usr/lib/python2.7/dist-packages/psutil/_common.py", line 85, in __get__
    ret = self.func(instance)
  File "/usr/lib/python2.7/dist-packages/psutil/__init__.py", line 345, in name
    name = self._platform_impl.get_process_name()
AttributeError: 'NoneType' object has no attribute '_platform_impl'
```
Some how the `self` object is not passed to the attributes getter method resulting in `None` ...
Those are the thing which are just stealing time :wink:

**Comment by masmu** [comment]
For now, every _pulseaudio_ instance get its own _pulseaudio-dlna_ session. I assume, if there are multiple users logged in there will be multiple _pulseaudio_ instances and therefore multiple _pulseaudio-dlna_ sessions. I never tested this in reality but from my point of view it should work.
One thing is still necessary: _pulseaudio-dlna_ has to choose a random available port for the HTTP server.

The current problem is how do we filter the display manager's _pulseaudio_ process. Otherwise _pulseaudio-dlna_ will try to attach a session to it all the time. This will fail and the exception is getting catched, but I guess you cannot call this good practice.

Is it reliable to assume that user ids are starting at 1000? In _ubuntu_ that is always the case but I am not sure if other distributions using that concept too.

**Comment by klaernie** [comment]
Well, it is safe to assume that all non-system users start at 500. This is the lowest UID boundary I have seen in practice (I think it was either redhat or suse).

You should consider, that this might break the system-mode of pulseaudio, not that this would be supported by the pulseaudio devs anyway. 

Also it is quite uncool, that the daemon mode won't support multiple users, but I think that is something to solve later.

**Comment by masmu** [comment]
Ok, I updated my branch to consider that, but I have to test it later when using _wily_ again.

> You should consider, that this might break the system-mode of pulseaudio, not that this would be supported by the pulseaudio devs anyway.

Right. :wink: 

> Also it is quite uncool, that the daemon mode won't support multiple users, but I think that is something to solve later.

+1 on my todo list.

**Pull request closed without merging**
