### PR TITLE
Added Samsung 32" Smart TV info

### PR DESCRIPTION
**Pull request by plaes**

### CODE REVIEW

**Comment by plaes** [comment]
I should probably mention that I tested with ffmpeg backend.

**Comment by masmu** [comment]
Thanks for the PR. But why did you add `netaddr` to _setup.py_?

Regarding the backend: It would be great if you could test your device again using the default backend.

**Comment by plaes** [comment]
`netaddr` requirement - ran `make`, activated virtual environment and started the app:

```
(pulseaudio-dlna) [plaes@solar pulseaudio-dlna]$ ./bin/pulseaudio-dlna 
Traceback (most recent call last):
  File "./bin/pulseaudio-dlna", line 11, in <module>
    load_entry_point('pulseaudio-dlna', 'console_scripts', 'pulseaudio-dlna')()
  File "/home/plaes/code/pulseaudio-dlna/pulseaudio_dlna/__main__.py", line 148, in main
    import pulseaudio_dlna.application
  File "/home/plaes/code/pulseaudio-dlna/pulseaudio_dlna/application.py", line 31, in <module>
    import pulseaudio_dlna.plugins.upnp
  File "/home/plaes/code/pulseaudio-dlna/pulseaudio_dlna/plugins/upnp/__init__.py", line 27, in <module>
    import pulseaudio_dlna.plugins.upnp.ssdp.discover
  File "/home/plaes/code/pulseaudio-dlna/pulseaudio_dlna/plugins/upnp/ssdp/discover.py", line 26, in <module>
    import pulseaudio_dlna.utils.network
  File "/home/plaes/code/pulseaudio-dlna/pulseaudio_dlna/utils/network.py", line 21, in <module>
    import netaddr
ImportError: No module named netaddr
```

**Comment by plaes** [comment]
Tested with default backend:
mp3 - OK
wav - FAIL
ogg - OK
flac	- OK
aac	- FAIL
opus -FAIL
l16	- FAIL

PS. Had to install following packages on Fedora: `vorbis-tools lame flac sox faac opus-tools` via `sudo dnf install`

**Pull request merged**
